# @package _global_

data: /mnt3/dataset/imagenet/ILSVRC/Data/CLS-LOC/
workers: 32

epochs: 100

arch: l_resnet101

start_epoch: 0
train_batch: 128
test_batch: 128
lr: 0.1
drop: 0.
schedule: [30,60,90]
gamma: 0.1
momentum: 0.9
weight_decay: 1e-4

checkpoint: checkpoints/imagenet/resnet101
print_freq: 100

norm: GN
use_ws: True  # Use weight-standardization

warmup: False  # train using lr/10 for the first epoch (based on official resent paper)

max_batch_size: 32  # max batch per single GPU

