# Datasets
data: cifar10
workers: 32

# General
print_freq: 10
manualSeed: 0
evaluate: False
pretrained: False
checkpoint:
resume:

wandb_off: False
checkpoint_off: False
extra_tags: ''

# Wandb related
notes: ''

# Ortho - Regularization
reg_type:
ortho_decay: 1e-2
force_num_groups: False
regularize_all: True

defaults:
  - _self_
  - model: resnet110